version: '3.8'

services:
  postgres:
    container_name: rinha-pg
    image: postgres
    hostname: db-rinha
    ports:
      - 5432:5432
    network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: rinha
      PG_DATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.2'
    #      memory: '180MB'

  api01: &api
    image: rinha-backend:latest
    hostname: api01
    environment:
      - DATABASE_URL=postgresql://postgres:docker@localhost:5432/rinha?schema=public
      - PORT=3000
    ports:
      - '8080:3000'
    network_mode: host
    build:
      context: .
    depends_on:
      - postgres
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.5'
    #      memory: '150MB'
  api02:
    <<: *api
    hostname: api02
    ports:
      - '8081:3001'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - '9999:9999'
    network_mode: host
    #deploy:
    #  resources:
    #    limits:
    #      cpus: '0.1'
    #      memory: '20MB'
